language: node_js
node_js:
  - 17

branches:
  only:
  - main

cache:
  directories:
  - node_modules

script:
  #- yarn lint
  - npm run build
  - mv build/index.html build/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  local_dir: build
  on:
    branch: main